#!/bin/bash

#SBATCH -J itp_hello_world
#SBATCH -p general
#SBATCH -o filename_%j.txt
#SBATCH -e filename_%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=emailaddr
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --time=10:00:00
#SBATCH --mem=150gb

######  Module commands #####
module load anaconda/python3.7/2019.03

# change dir of the code
cd /N/u/iuusername/Carbonate/intro_to_python_project

python helloworldcode.py

